#!/bin/bash
# Do PreCompact Hook Wrapper - Generated by convert
# This script forwards stdin JSON to the godo hook compact command.
#
# Compact responsibilities (GODO_HOOK_ARCHITECT.md Section 2.2):
#   - Preserve context snapshots during context compression (/compact)
#   - Ensure persona state, mode state, and checklist state survive compaction
#
# This hook fires on PostToolUse (no matcher = all) as a separate entry,
# distinct from the main .* PostToolUse hook. It handles compaction-specific
# snapshot preservation that the main PostToolUse hook does not cover.
#
# Project-local hook: .claude/hooks/do/handle-compact.sh

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Try godo command in PATH
if command -v godo &> /dev/null; then
	exec godo hook compact < "$temp_file"
fi

# Try Go bin path
if [ -f "${GOPATH:-$HOME/go}/bin/godo" ]; then
	exec "${GOPATH:-$HOME/go}/bin/godo" hook compact < "$temp_file"
fi

# Try /usr/local/bin fallback
if [ -f "/usr/local/bin/godo" ]; then
	exec "/usr/local/bin/godo" hook compact < "$temp_file"
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
