#!/bin/bash
# Do UserPromptSubmit Hook Wrapper - Generated by convert
# This script forwards stdin JSON to the godo hook user-prompt-submit command.
#
# UserPromptSubmit responsibilities (GODO_HOOK_ARCHITECT.md Section 2.4):
#   - Inject persona honorific/speech style reminder via additionalContext
#     (e.g., "반드시 '승민선배'로 호칭할 것. 말투: 반말+존댓말 혼합")
#   - Inject current mode reminder
#     (e.g., "현재 실행 모드: do (응답 접두사: [Do])")
#
# This hook is the "last line of defense" for persona persistence.
# It survives /clear and /compact because it fires on every user prompt.
# MoAI does NOT have this hook -- it is Do-exclusive.
#
# Dual injection mechanism (Section 2.5):
#   Path 1: UserPromptSubmit -> survives /clear
#   Path 2: PostToolUse .* -> maintains persona during tool sequences
#
# Project-local hook: .claude/hooks/do/handle-user-prompt-submit.sh

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Try godo command in PATH
if command -v godo &> /dev/null; then
	exec godo hook user-prompt-submit < "$temp_file"
fi

# Try Go bin path
if [ -f "${GOPATH:-$HOME/go}/bin/godo" ]; then
	exec "${GOPATH:-$HOME/go}/bin/godo" hook user-prompt-submit < "$temp_file"
fi

# Try /usr/local/bin fallback
if [ -f "/usr/local/bin/godo" ]; then
	exec "/usr/local/bin/godo" hook user-prompt-submit < "$temp_file"
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
