#!/bin/bash
# Do Stop Hook Wrapper - Generated by convert
# This script forwards stdin JSON to the godo hook stop command.
#
# Stop responsibilities (GODO_HOOK_ARCHITECT.md Section 2.4):
#   - Check stop_hook_active from stdin JSON
#     - If true -> return {} immediately (infinite loop prevention)
#   - Scan .do/jobs/ for most recent date's checklist.md
#   - Parse 6-state symbols and count: [ ] [~] [*] [!] [o] [x]
#   - Decision:
#     - All complete [o] -> allow exit
#     - In-progress [~] or blocked [!] exists, incomplete -> block exit
#       {"decision": "block", "reason": "active checklist (3/5 done, 1 in-progress...)"}
#     - All items pending [ ] -> allow exit (unstarted work doesn't block)
#   - No active checklist -> return {} (allow exit)
#
# Key design principle: Only "started work" blocks exit.
# Plans with all-pending checklists (all [ ]) do NOT block,
# allowing users to plan in one session and execute in the next.
#
# Project-local hook: .claude/hooks/do/handle-stop.sh

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Try godo command in PATH
if command -v godo &> /dev/null; then
	exec godo hook stop < "$temp_file"
fi

# Try Go bin path
if [ -f "${GOPATH:-$HOME/go}/bin/godo" ]; then
	exec "${GOPATH:-$HOME/go}/bin/godo" hook stop < "$temp_file"
fi

# Try /usr/local/bin fallback
if [ -f "/usr/local/bin/godo" ]; then
	exec "/usr/local/bin/godo" hook stop < "$temp_file"
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
