#!/bin/bash
# Do SessionStart Hook Wrapper - Generated by convert
# This script forwards stdin JSON to the godo hook session-start command.
#
# SessionStart responsibilities (GODO_HOOK_ARCHITECT.md Section 2.4):
#   - Read current mode from .do/.current-mode (do/focus/team)
#   - Apply persona spinner verbs based on DO_PERSONA type
#   - Check latest godo version via GitHub API (3s timeout)
#   - Detect project info (language, project name from go.mod, package.json, etc.)
#   - Output systemMessage with mode and project info
#
# Key constraint: SessionStart READS mode state only. Never overwrites.
# Project-local hook: .claude/hooks/do/handle-session-start.sh

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Try godo command in PATH
if command -v godo &> /dev/null; then
	exec godo hook session-start < "$temp_file"
fi

# Try Go bin path
if [ -f "${GOPATH:-$HOME/go}/bin/godo" ]; then
	exec "${GOPATH:-$HOME/go}/bin/godo" hook session-start < "$temp_file"
fi

# Try /usr/local/bin fallback
if [ -f "/usr/local/bin/godo" ]; then
	exec "/usr/local/bin/godo" hook session-start < "$temp_file"
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
