#!/bin/bash
# Do SessionEnd Hook Wrapper - Generated by convert
# This script forwards stdin JSON to the godo hook session-end command.
#
# SessionEnd responsibilities (GODO_HOOK_ARCHITECT.md Section 2.4):
#   Runs after session termination with 2-second overall timeout.
#   Executes in parallel goroutines:
#
#   [goroutine 1] Rank API session data submission (best-effort, non-blocking)
#     - Auth check -> transcript parsing -> token usage aggregation -> API submit
#
#   [goroutine 2] Git info collection
#     - Current branch, uncommitted file count, commits in last hour
#
#   Saves snapshot to .do/memory/last-session-state.json
#   Outputs systemMessage (uncommitted WARNING, recent commit count)
#
# MoAI does NOT have UserPromptSubmit or SessionEnd hooks.
# These two are Do-exclusive, providing pre-prompt persona injection
# and post-session cleanup respectively.
#
# Project-local hook: .claude/hooks/do/handle-session-end.sh

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Try godo command in PATH
if command -v godo &> /dev/null; then
	exec godo hook session-end < "$temp_file"
fi

# Try Go bin path
if [ -f "${GOPATH:-$HOME/go}/bin/godo" ]; then
	exec "${GOPATH:-$HOME/go}/bin/godo" hook session-end < "$temp_file"
fi

# Try /usr/local/bin fallback
if [ -f "/usr/local/bin/godo" ]; then
	exec "/usr/local/bin/godo" hook session-end < "$temp_file"
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
