#!/bin/bash
# Do PreToolUse Hook Wrapper - Generated by convert
# This script forwards stdin JSON to the godo hook pre-tool command.
#
# PreToolUse responsibilities (GODO_HOOK_ARCHITECT.md Section 2.4):
#   Matcher: Write|Edit|Bash
#   Returns: "allow", "deny", or "ask"
#
#   [Bash command inspection]
#     - denyBashPatterns match -> "deny" (dangerous command blocked)
#     - askBashPatterns match  -> "ask"  (user confirmation required)
#
#   [Write/Edit file access inspection]
#     - Resolve file path to absolute
#     - Path traversal outside project directory -> block
#     - denyFilePatterns match -> protected file blocked (.env, credentials)
#     - askFilePatterns match  -> important config file confirmation
#     - Secret pattern detection in content (API keys, certs, etc.)
#
#   [AST security scan] (Write only, optional)
#     - Check if ast-grep (sg) is installed
#     - Write content to temp file -> sg scan --json (10s timeout)
#     - Error severity found -> "deny"
#
#   [Checklist hierarchy validation] (Write only)
#     - Writing to .do/jobs/**/checklists/*.md:
#       - plan.md must exist -> else VIOLATION block
#       - checklist.md must exist -> else VIOLATION block
#
# Project-local hook: .claude/hooks/do/handle-pre-tool.sh

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Try godo command in PATH
if command -v godo &> /dev/null; then
	exec godo hook pre-tool < "$temp_file"
fi

# Try Go bin path
if [ -f "${GOPATH:-$HOME/go}/bin/godo" ]; then
	exec "${GOPATH:-$HOME/go}/bin/godo" hook pre-tool < "$temp_file"
fi

# Try /usr/local/bin fallback
if [ -f "/usr/local/bin/godo" ]; then
	exec "/usr/local/bin/godo" hook pre-tool < "$temp_file"
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
