#!/bin/bash
# Do SubagentStop Hook Wrapper - Generated by convert
# This script forwards stdin JSON to the godo hook subagent-stop command.
#
# SubagentStop responsibilities (GODO_HOOK_ARCHITECT.md Section 2.4):
#   - Parse agent_id, status, description from stdin JSON
#   - Load state from .do/cache/background-tasks.json
#   - Record completion time and elapsed duration
#   - Recalculate overall progress
#   - Output progress bar to stderr: [########--------] 4/8 (50%)
#   - On full completion (completed >= total):
#       - Output success/failure summary, total elapsed time, failed task list
#       - Reset state (active = false)
#   - Return {"continue": true}
#
# This replaces MoAI's handle-agent-hook.sh which dispatches to
# moai hook agent <action> with specific agent lifecycle actions
# (ddd-pre-transformation, spec-completion, etc.).
# Do simplifies this to a single subagent-stop event that tracks
# all agent task progress uniformly via checklist state files.
#
# Project-local hook: .claude/hooks/do/handle-subagent-stop.sh

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Try godo command in PATH
if command -v godo &> /dev/null; then
	exec godo hook subagent-stop < "$temp_file"
fi

# Try Go bin path
if [ -f "${GOPATH:-$HOME/go}/bin/godo" ]; then
	exec "${GOPATH:-$HOME/go}/bin/godo" hook subagent-stop < "$temp_file"
fi

# Try /usr/local/bin fallback
if [ -f "/usr/local/bin/godo" ]; then
	exec "/usr/local/bin/godo" hook subagent-stop < "$temp_file"
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
