#!/bin/bash
# Do PostToolUse Hook Wrapper - Generated by convert
# This script forwards stdin JSON to the godo hook post-tool-use command.
#
# PostToolUse responsibilities (GODO_HOOK_ARCHITECT.md Section 2.4):
#   Matcher: .* (ALL tools -- Do's intentional philosophical decision)
#
#   Why .* instead of Write|Edit (Section 2.3):
#     MoAI uses Write|Edit matcher for token efficiency.
#     Do uses .* to maintain persona consistency during long read-search
#     sequences (Read -> Grep -> Glob -> ...). Without .*, persona drifts
#     during reading-only sequences. Persona consistency > token efficiency.
#
#   8 sub-processors executed sequentially:
#
#   [1. Plan file pipeline]
#     Write/Edit on plan.md:
#       - Written to .do/plans/ -> move to .do/jobs/{YY}/{MM}/{DD}/{slug}/plan.md
#       - Auto-create checklist.md stub (with 6-state legend)
#       - Auto-create checklists/ subdirectory
#       - Reminder: "write the checklist"
#
#   [2. AI footer removal]
#     Bash containing "git commit":
#       - Remove "Co-Authored-By: Claude Code" line from latest commit
#       - (Preserved if DO_AI_FOOTER=true)
#
#   [3. Persona injection]
#     Build persona from DO_PERSONA + DO_USER_NAME
#     Add honorific + speech style reminder to additionalContext
#
#   [4. Unfilled checklist detection]
#     plan.md exists but checklist.md is stub -> "[HARD] write checklist" reminder
#
#   [5. Undecomposed checklist detection]
#     checklist.md written but no checklists/*.md -> "[HARD] decompose" reminder
#
#   [6. Agent uncommitted change detection]
#     tool_name is "Task":
#       git status for uncommitted changes outside .do/ -> "[HARD] commit" reminder
#
#   [7. Plan modification sync prompt]
#     Edit on plan.md:
#       "update checklist too" reminder
#
#   [8. Auto-lint]
#     Write/Edit on code files (.go, .ts, .py, etc.):
#       Lint results added to additionalContext
#
# Project-local hook: .claude/hooks/do/handle-post-tool-use.sh

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Try godo command in PATH
if command -v godo &> /dev/null; then
	exec godo hook post-tool-use < "$temp_file"
fi

# Try Go bin path
if [ -f "${GOPATH:-$HOME/go}/bin/godo" ]; then
	exec "${GOPATH:-$HOME/go}/bin/godo" hook post-tool-use < "$temp_file"
fi

# Try /usr/local/bin fallback
if [ -f "/usr/local/bin/godo" ]; then
	exec "/usr/local/bin/godo" hook post-tool-use < "$temp_file"
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
